name: github-auto-follow-unfollow-view-user-list

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: github-auto-follow-unfollow-view-user-list
        uses: iwdath/github-auto-follow-unfollow-view-user-list@main
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ github.repository }}
          isReadmeUpdate: true
          safeUserList: 'Liu-Yong-HK,Huniko-Team'
